import { Router } from "express";
import { authRouter } from "./auth.routes.js";
import { catalogRouter } from "./catalog.routes.js";
import { cartRouter } from "./cart.routes.js";
import { couponRouter } from "./coupon.routes.js";
import { orderRouter } from "./order.routes.js";
import { paymentRouter } from "./payment.routes.js";
import { localizationRouter } from "./localization.routes.js";
import { sellerRouter } from "./seller.routes.js";
import { adminRouter } from "./admin.routes.js";
import { addonRouter } from "./addon.routes.js";
import { customerRouter } from "./customer.routes.js";
import { reviewRouter } from "./review.routes.js";
import { conversationRouter } from "./conversation.routes.js";
import { cmsRouter } from "./cms.routes.js";
import { attributeRouter } from "./attribute.routes.js";
import { flashDealRouter } from "./flashdeal.routes.js";
import { pickupPointRouter } from "./pickuppoint.routes.js";
import { newsletterRouter } from "./newsletter.routes.js";
import { digitalProductRouter } from "./digitalproduct.routes.js";
import { reportRouter } from "./report.routes.js";
import { homepageRouter } from "./homepage.routes.js";

export const apiRouter = Router();

apiRouter.get("/health", (_req, res) => {
  res.json({ status: "ok", service: "api", timestamp: new Date().toISOString() });
});

apiRouter.use("/auth", authRouter);
apiRouter.use("/catalog", catalogRouter);
apiRouter.use("/catalog", attributeRouter);
apiRouter.use("/cart", cartRouter);
apiRouter.use("/coupons", couponRouter);
apiRouter.use("/orders", orderRouter);
apiRouter.use("/payments", paymentRouter);
apiRouter.use("/localization", localizationRouter);
apiRouter.use("/seller", sellerRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/addons", addonRouter);
apiRouter.use("/me", customerRouter);
apiRouter.use("/reviews", reviewRouter);
apiRouter.use("/conversations", conversationRouter);
apiRouter.use("/cms", cmsRouter);
apiRouter.use("/flash-deals", flashDealRouter);
apiRouter.use("/pickup-points", pickupPointRouter);
apiRouter.use("/newsletter", newsletterRouter);
apiRouter.use("/digital-products", digitalProductRouter);
apiRouter.use("/admin/reports", reportRouter);
apiRouter.use("/homepage", homepageRouter);
