"use client";

import { useMemo, useState } from "react";
import { entityDefinitions, type EntityDefinition, type EntityName } from "@/lib/workspace";
import { titleFromSlug } from "@/lib/utils";

function renderValue(value: unknown) {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return <span className="status-pill">{value ? "Enabled" : "Disabled"}</span>;
  if (typeof value === "object") return JSON.stringify(value);
  const text = String(value); return text.length > 100 ? `${text.slice(0, 100)}…` : text;
}
function editableValue(value: unknown): string { if (value === null || value === undefined) return ""; return typeof value === "object" ? JSON.stringify(value) : String(value); }
function parseValue(value: string): unknown { const trimmed=value.trim();if(trimmed==="")return null;if(trimmed==="true")return true;if(trimmed==="false")return false;if(/^-?\d+(\.\d+)?$/.test(trimmed))return Number(trimmed);if((trimmed.startsWith("[")&&trimmed.endsWith("]"))||(trimmed.startsWith("{")&&trimmed.endsWith("}"))){try{return JSON.parse(trimmed)}catch{}}return trimmed; }

function MediaField({ name, value }: { name: "thumbnail" | "photos"; value: unknown }) {
  const [stored, setStored] = useState(editableValue(value)); const [message, setMessage] = useState("");
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const file=event.target.files?.[0];if(!file)return;setMessage("Uploading…");const form=new FormData();form.set("file",file);const response=await fetch("/api/uploads",{method:"POST",body:form});const result=await response.json();if(!response.ok){setMessage(result.message||"Upload failed.");return}if(name==="photos"){let current:string[]=[];try{const parsed=JSON.parse(stored||"[]");if(Array.isArray(parsed))current=parsed.map(String)}catch{}setStored(JSON.stringify([...current,result.path]));}else setStored(result.path);setMessage("Image uploaded."); }
  return <div className="field"><label>{titleFromSlug(name)}</label><input type="hidden" name={name} value={stored}/><input className="form-control" type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/><textarea className="form-control" rows={name==="photos"?3:1} value={stored} onChange={(event)=>setStored(event.target.value)}/>{message&&<small>{message}</small>}</div>;
}

export function EntityTable({ entity, rows: initialRows, title, mode }: { entity: EntityName; rows: Record<string, unknown>[]; title?: string; mode?: "admin" | "seller" }) {
  const [rows,setRows]=useState(initialRows);const [editing,setEditing]=useState<Record<string,unknown>|null>(null);const [creating,setCreating]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
  const definition:EntityDefinition=entityDefinitions[entity];const columns=useMemo(()=>rows[0]?Object.keys(rows[0]):[],[rows]);
  const formColumns=definition.fields.filter((column)=>!["_id","createdAt","updatedAt","deletedAt"].includes(column)&&!column.includes(".")&&!Object.prototype.hasOwnProperty.call(definition.baseFilter||{},column)&&!(mode==="seller"&&["seller","owner","addedBy","verificationStatus","active"].includes(column)));
  const canUpdate=Boolean(mode)&&!definition.readOnly;const canCreate=canUpdate&&!definition.createDisabled&&(mode==="admin"||entity==="products");const canDelete=canUpdate&&!definition.deleteDisabled&&(mode==="admin"||entity==="products");
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const isEditing=Boolean(editing?._id);const values=Object.fromEntries([...new FormData(event.currentTarget).entries()].flatMap(([key,value])=>!isEditing&&String(value).trim()===""?[]:[[key,parseValue(String(value))]]));const response=await fetch(`/api/manage/${entity}`,{method:isEditing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(isEditing?{id:editing!._id,...values}:values)});const result=await response.json();if(!response.ok){setMessage(result.message||"The record could not be saved.");setBusy(false);return}if(isEditing)setRows((current)=>current.map((row)=>row._id===editing!._id?{...row,...values}:row));else setRows((current)=>[{_id:result.id,...values,createdAt:new Date().toISOString()},...current]);setEditing(null);setCreating(false);setBusy(false);setMessage("Saved successfully.");}
  async function remove(row:Record<string,unknown>){if(!row._id||!window.confirm("Remove this record? Catalog and account records are soft-deleted where recovery matters."))return;setBusy(true);setMessage("");const response=await fetch(`/api/manage/${entity}?id=${encodeURIComponent(String(row._id))}`,{method:"DELETE"});const result=await response.json();if(!response.ok)setMessage(result.message||"The record could not be removed.");else{setRows((current)=>current.filter((candidate)=>candidate._id!==row._id));setMessage("Record removed.")}setBusy(false);}
  const formRecord=editing||{};
  return <section className="content-card"><div className="workspace-toolbar"><div><span className="eyebrow">Data management</span><h2>{title||titleFromSlug(entity)}</h2></div><div className="toolbar-actions"><form><input className="form-control" name="q" placeholder="Search records"/><button className="button">Search</button></form>{canCreate&&<button className="button button-primary" onClick={()=>{setCreating(true);setEditing(null)}}>Add record</button>}</div></div>{message&&<div className={message.includes("success")||message.includes("removed")?"callout":"form-error"}>{message}</div>}{!rows.length?<div className="empty-state" style={{padding:35}}><h2>No records found</h2><p>There are no matching MongoDB documents in this section.</p>{canCreate&&<button className="button button-primary" onClick={()=>setCreating(true)}>Create the first record</button>}</div>:<div className="table-wrap"><table className="data-table"><thead><tr>{columns.map((column)=><th key={column}>{titleFromSlug(column)}</th>)}{(canUpdate||canDelete)&&<th>Actions</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row._id??index)}>{columns.map((column)=><td key={column}>{renderValue(row[column])}</td>)}{(canUpdate||canDelete)&&<td><div className="table-actions">{canUpdate&&<button className="mini-button" onClick={()=>{setEditing(row);setCreating(false)}}>Edit</button>}{canDelete&&<button className="mini-button danger" disabled={busy} onClick={()=>remove(row)}>Delete</button>}</div></td>}</tr>)}</tbody></table></div>}{((canCreate&&creating)||(canUpdate&&editing))&&<div className="modal-backdrop" onMouseDown={(event)=>{if(event.target===event.currentTarget){setEditing(null);setCreating(false)}}}><div className="record-modal"><div className="modal-heading"><div><span className="eyebrow">{editing?"Update document":"New document"}</span><h2>{title||titleFromSlug(entity)}</h2></div><button className="modal-close" onClick={()=>{setEditing(null);setCreating(false)}} aria-label="Close">×</button></div><form className="record-form" onSubmit={save}>{formColumns.length?formColumns.map((column)=>entity==="products"&&(column==="thumbnail"||column==="photos")?<MediaField key={column} name={column} value={formRecord[column]}/>:<div className="field" key={column}><label>{titleFromSlug(column)}</label><textarea className="form-control" name={column} required={definition.requiredFields?.includes(column)} rows={column==="description"||column==="value"||column==="variants"?4:1} defaultValue={editableValue(formRecord[column])}/></div>):<p>No writable fields are available for this collection.</p>}<div className="modal-actions"><button type="button" className="button" onClick={()=>{setEditing(null);setCreating(false)}}>Cancel</button><button className="button button-primary" disabled={busy||!formColumns.length}>{busy?"Saving…":"Save record"}</button></div></form></div></div>}</section>;
}
