"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Money } from "@/components/preferences-provider";

type OrderData = Record<string, any>;
export function OrderWorkflow({ workspace }: { workspace: "customer" | "seller" | "admin" }) {
  const [orders,setOrders]=useState<OrderData[]>([]);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  async function refresh(){const response=await fetch("/api/account/orders");const result=await response.json();if(response.ok)setOrders(result.data||[]);else setMessage(result.message||"Orders could not be loaded.")}
  useEffect(()=>{refresh().catch(()=>setMessage("Orders could not be loaded."))},[]);
  async function patch(path:string,body:Record<string,unknown>,success:string){setBusy(true);const response=await fetch(`/api/account/orders/${path}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(response.ok?success:result.message||"Order could not be updated.");if(response.ok)await refresh();setBusy(false)}
  async function updateStatus(orderId:string,status:string,itemId?:string){await patch("status",{orderId,itemId,status},"Order updated.")}
  async function markPaid(orderId:string){await patch("payment",{orderId,status:"paid"},"Payment marked paid.")}
  async function review(event:React.FormEvent<HTMLFormElement>,orderId:string,productId:string){event.preventDefault();setBusy(true);const values=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/account/orders/review",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({orderId,productId,...values})});const result=await response.json();setMessage(response.ok?"Review saved.":result.message||"Review could not be saved.");setBusy(false)}
  return <section className="content-card"><span className="eyebrow">Order management</span><h2>{workspace==="customer"?"Purchase history":workspace==="seller"?"Seller orders":"Marketplace orders"}</h2>{message&&<div className={/updated|saved|marked/i.test(message)?"callout":"form-error"}>{message}</div>}<div className="form-grid">{orders.map((order)=><article className="callout" key={order._id}><div className="workspace-toolbar"><div><strong>{order.code}</strong><p>{new Date(order.createdAt).toLocaleString()} · <Money value={Number(order.total)}/></p></div><div><span>{order.status}</span> · <span>{order.payment?.status}</span> <Link className="mini-button" href={`/invoice/${encodeURIComponent(order._id)}`}>Invoice</Link>{workspace==="admin"&&order.payment?.status!=="paid"&&<button className="mini-button" disabled={busy} onClick={()=>markPaid(order._id)}>Mark paid</button>}{workspace==="customer"&&order.status==="pending"&&order.payment?.status==="unpaid"&&<button className="mini-button danger" disabled={busy} onClick={()=>updateStatus(order._id,"cancelled")}>Cancel</button>}</div></div>{order.items?.map((item:OrderData)=><div key={item._id} className="summary-row"><div><strong>{item.name}</strong><small>{item.variation?`${item.variation} · `:""}{item.quantity} × <Money value={Number(item.unitPrice)}/></small></div><div><span>{item.deliveryStatus}</span>{workspace!=="customer"&&item.deliveryStatus!=="delivered"&&item.deliveryStatus!=="cancelled"&&<select className="form-control" disabled={busy} value="" onChange={(event)=>{if(event.target.value)updateStatus(order._id,event.target.value,item._id)}}><option value="">Update status</option>{["confirmed","processing","shipped","delivered","cancelled"].map((status)=><option key={status} value={status}>{status}</option>)}</select>}{workspace==="customer"&&item.deliveryStatus==="delivered"&&item.paymentStatus==="paid"&&item.product&&<form className="toolbar-actions" onSubmit={(event)=>review(event,order._id,item.product)}><select className="form-control" name="rating" defaultValue="5">{[5,4,3,2,1].map((rating)=><option key={rating} value={rating}>{rating} stars</option>)}</select><input className="form-control" name="comment" placeholder="Your review" maxLength={2000}/><button className="mini-button" disabled={busy}>Save review</button></form>}</div></div>)}</article>)}{!orders.length&&<div className="empty-state"><h3>No orders found</h3><p>Orders for this account will appear here.</p></div>}</div></section>;
}
