import crypto from "node:crypto";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import bcrypt from "bcryptjs";
import mongoose from "mongoose";

const root=fileURLToPath(new URL("../",import.meta.url));const port=Number(process.env.SMOKE_PORT||3210);const base=`http://127.0.0.1:${port}`;const runId=crypto.randomUUID();const customerEmail=`smoke-customer-${runId}@example.invalid`;const sellerEmail=`smoke-seller-${runId}@example.invalid`;const adminEmail=`smoke-admin-${runId}@example.invalid`;const password=`Smoke-${crypto.randomUUID()}!`;let output="";let server;let originalVerification;
const ids={category:new mongoose.Types.ObjectId(),seller:new mongoose.Types.ObjectId(),admin:new mongoose.Types.ObjectId(),shop:new mongoose.Types.ObjectId(),product:new mongoose.Types.ObjectId()};
function wait(ms){return new Promise((resolve)=>setTimeout(resolve,ms))}function assert(condition,message){if(!condition)throw new Error(message)}
async function request(path,expectedStatus,options={}){const response=await fetch(`${base}${path}`,{redirect:"manual",...options});if(response.status!==expectedStatus)throw new Error(`${options.method||"GET"} ${path}: expected ${expectedStatus}, received ${response.status}: ${await response.text()}`);return response}
function cookie(response){const value=response.headers.get("set-cookie")?.split(";",1)[0];assert(value?.startsWith("v4local_session="),"Authentication did not return a session cookie");return value}
function jsonHeaders(token){return {"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})}}

try{
  await mongoose.connect(process.env.MONGODB_URI,{dbName:process.env.MONGODB_DB||undefined,serverSelectionTimeoutMS:10_000});const db=mongoose.connection.db;const now=new Date();
  originalVerification=await db.collection("settings").findOne({key:"business.email_verification"});await db.collection("settings").updateOne({key:"business.email_verification"},{$set:{value:"0"}});
  const hash=await bcrypt.hash(password,12);
  await db.collection("users").insertMany([{_id:ids.seller,name:"Runtime Smoke Seller",email:sellerEmail,passwordHash:hash,role:"seller",status:"active",provider:"password",emailVerifiedAt:now,balance:0,createdAt:now,updatedAt:now},{_id:ids.admin,name:"Runtime Smoke Admin",email:adminEmail,passwordHash:hash,role:"admin",status:"active",provider:"password",emailVerifiedAt:now,balance:0,createdAt:now,updatedAt:now}]);
  await db.collection("categories").insertOne({_id:ids.category,name:"Runtime Smoke Category",slug:`runtime-smoke-${runId}`,parent:null,active:true,commissionRate:20,createdAt:now,updatedAt:now});
  await db.collection("shops").insertOne({_id:ids.shop,owner:ids.seller,name:"Runtime Smoke Shop",slug:`runtime-smoke-shop-${runId}`,shippingCost:0,adminToPay:0,verificationStatus:"approved",active:true,createdAt:now,updatedAt:now});
  await db.collection("products").insertOne({_id:ids.product,name:"Runtime Smoke Product",slug:`runtime-smoke-product-${runId}`,seller:ids.seller,addedBy:"seller",category:ids.category,unitPrice:100,purchasePrice:60,discount:0,discountType:"amount",tax:0,taxType:"amount",stock:10,sales:0,unit:"pc",minQuantity:1,shippingType:"free",shippingCost:0,rating:0,published:true,featured:false,todaysDeal:false,digital:false,variants:[],photos:[],createdAt:now,updatedAt:now});

  server=spawn(process.execPath,["server.mjs"],{cwd:root,env:{...process.env,PORT:String(port)},stdio:["ignore","pipe","pipe"]});server.stdout.on("data",(chunk)=>{output=`${output}${chunk}`.slice(-6000)});server.stderr.on("data",(chunk)=>{output=`${output}${chunk}`.slice(-6000)});
  let ready=false;for(let attempt=0;attempt<120;attempt+=1){if(server.exitCode!==null)break;try{if((await fetch(`${base}/healthz`)).ok){ready=true;break}}catch{}await wait(500)}assert(ready,`Server did not become healthy.\n${output}`);
  await request("/",200);await request("/products",200);await request("/compare",200);await request("/forgot-password",200);await request("/api/health",200);await request("/api/v1/products",200);
  const preferences=await request("/api/preferences",200,{method:"POST",headers:jsonHeaders(),body:JSON.stringify({currency:"USD",language:"bd"})});const preferenceCookies=preferences.headers.get("set-cookie")||"";assert(preferenceCookies.includes("v4_currency=USD")&&preferenceCookies.includes("v4_locale=bd"),"Language/currency preferences were not persisted");

  const registration=await request("/api/auth/register",201,{method:"POST",headers:jsonHeaders(),body:JSON.stringify({name:"Runtime Smoke Customer",email:customerEmail,password,passwordConfirmation:password,role:"customer"})});const customerCookie=cookie(registration);
  await request("/dashboard",200,{headers:{cookie:customerCookie}});await request("/api/v1/auth/user",200,{headers:{cookie:customerCookie}});await request("/api/manage/products",403,{headers:{cookie:customerCookie}});
  await request("/api/account/addresses",201,{method:"POST",headers:{...jsonHeaders(),cookie:customerCookie},body:JSON.stringify({label:"Home",recipient:"Runtime Smoke Customer",address:"1 Test Street",city:"Ahmedabad",state:"Gujarat",postalCode:"380001",country:"India",phone:"9999999999",isDefault:true})});
  const orderKey=crypto.randomUUID();const checkout={name:"Runtime Smoke Customer",email:customerEmail,address:"1 Test Street",city:"Ahmedabad",state:"Gujarat",postal_code:"380001",country:"India",phone:"9999999999",payment:"cod",idempotencyKey:orderKey,lines:[{productId:String(ids.product),quantity:2}]};
  const placed=await request("/api/orders",201,{method:"POST",headers:{...jsonHeaders(),cookie:customerCookie,"idempotency-key":orderKey},body:JSON.stringify(checkout)});const firstCode=(await placed.json()).code;assert(firstCode,"Web checkout did not return an order code");
  const repeated=await request("/api/orders",200,{method:"POST",headers:{...jsonHeaders(),cookie:customerCookie,"idempotency-key":orderKey},body:JSON.stringify(checkout)});assert((await repeated.json()).repeated===true,"Idempotent retry was not recognized");
  let product=await db.collection("products").findOne({_id:ids.product});let shop=await db.collection("shops").findOne({_id:ids.shop});assert(product.stock===8&&product.sales===2,"Web checkout did not update stock and sales exactly once");assert(shop.adminToPay===-40,"COD marketplace commission was not recorded correctly");

  const apiLogin=await request("/api/v1/auth/login",200,{method:"POST",headers:jsonHeaders(),body:JSON.stringify({email:customerEmail,password})});const accessToken=(await apiLogin.json()).access_token;assert(accessToken,"Mobile login did not issue an API token");
  await request("/api/v1/carts/add",200,{method:"POST",headers:jsonHeaders(accessToken),body:JSON.stringify({product_id:String(ids.product),quantity:1})});
  const mobilePlaced=await request("/api/v1/payments/pay/cod",201,{method:"POST",headers:{...jsonHeaders(accessToken),"idempotency-key":crypto.randomUUID()},body:JSON.stringify({shipping_address:JSON.stringify({name:"Runtime Smoke Customer",email:customerEmail,address:"1 Test Street",city:"Ahmedabad",state:"Gujarat",postal_code:"380001",country:"India",phone:"9999999999"}),payment_type:"cash_on_delivery"})});const secondCode=(await mobilePlaced.json()).data.code;assert(secondCode,"Mobile checkout did not return an order code");
  const cartAfter=await db.collection("carts").findOne({user:(await db.collection("users").findOne({email:customerEmail}))._id});assert(!cartAfter,"Mobile checkout did not clear the MongoDB cart");
  const secondOrder=await db.collection("orders").findOne({code:secondCode});await request("/api/account/orders/status",200,{method:"PATCH",headers:{...jsonHeaders(),cookie:customerCookie},body:JSON.stringify({orderId:String(secondOrder._id),status:"cancelled"})});
  product=await db.collection("products").findOne({_id:ids.product});shop=await db.collection("shops").findOne({_id:ids.shop});assert(product.stock===8&&product.sales===2,"COD cancellation did not restore inventory");assert(shop.adminToPay===-40,"COD cancellation did not reverse only its commission");

  const sellerLogin=await request("/api/auth/login",200,{method:"POST",headers:jsonHeaders(),body:JSON.stringify({email:sellerEmail,password})});const sellerCookie=cookie(sellerLogin);const firstOrder=await db.collection("orders").findOne({code:firstCode});const sellerItem=firstOrder.items.find((item)=>String(item.seller)===String(ids.seller));await request("/api/account/orders/status",200,{method:"PATCH",headers:{...jsonHeaders(),cookie:sellerCookie},body:JSON.stringify({orderId:String(firstOrder._id),itemId:String(sellerItem._id),status:"confirmed"})});
  const adminLogin=await request("/api/auth/login",200,{method:"POST",headers:jsonHeaders(),body:JSON.stringify({email:adminEmail,password})});const adminCookie=cookie(adminLogin);await request("/api/account/orders/payment",200,{method:"PATCH",headers:{...jsonHeaders(),cookie:adminCookie},body:JSON.stringify({orderId:String(firstOrder._id),status:"paid"})});await request(`/invoice/${firstOrder._id}`,200,{headers:{cookie:customerCookie}});await request(`/track_your_order?code=${encodeURIComponent(firstCode)}&contact=${encodeURIComponent(customerEmail)}`,200);
  await request("/api/v1/auth/user",200,{headers:{authorization:`Bearer ${accessToken}`}});await request("/api/v1/auth/logout",200,{headers:{authorization:`Bearer ${accessToken}`}});await request("/api/v1/auth/user",401,{headers:{authorization:`Bearer ${accessToken}`}});
  console.log("Runtime smoke test passed: public routes, preferences, registration/session, bearer auth, role authorization, addresses, web/mobile COD, idempotency, stock, commission, cancellation, seller status, admin payment, invoice, tracking, and logout.");
}finally{
  if(server){server.kill("SIGTERM");await Promise.race([new Promise((resolve)=>server.once("exit",resolve)),wait(12_000)]);if(server.exitCode===null)server.kill("SIGKILL")}
  if(mongoose.connection.readyState!==1&&process.env.MONGODB_URI)await mongoose.connect(process.env.MONGODB_URI,{dbName:process.env.MONGODB_DB||undefined,serverSelectionTimeoutMS:10_000}).catch(()=>undefined);
  if(mongoose.connection.readyState===1){const db=mongoose.connection.db;const testUsers=await db.collection("users").find({email:{$in:[customerEmail,sellerEmail,adminEmail]}}).project({_id:1}).toArray();const userIds=testUsers.map((user)=>user._id);const testOrders=await db.collection("orders").find({$or:[{customer:{$in:userIds}},{"items.seller":ids.seller}]}).project({_id:1}).toArray();const orderIds=testOrders.map((order)=>order._id);await Promise.allSettled([db.collection("sellerledgers").deleteMany({order:{$in:orderIds}}),db.collection("couponusages").deleteMany({order:{$in:orderIds}}),db.collection("orders").deleteMany({_id:{$in:orderIds}}),db.collection("addresses").deleteMany({user:{$in:userIds}}),db.collection("wishlists").deleteMany({user:{$in:userIds}}),db.collection("carts").deleteMany({user:{$in:userIds}}),db.collection("apitokens").deleteMany({user:{$in:userIds}}),db.collection("accounttokens").deleteMany({user:{$in:userIds}}),db.collection("reviews").deleteMany({user:{$in:userIds}}),db.collection("products").deleteOne({_id:ids.product}),db.collection("shops").deleteOne({_id:ids.shop}),db.collection("categories").deleteOne({_id:ids.category}),db.collection("users").deleteMany({_id:{$in:userIds}})]);if(originalVerification)await db.collection("settings").replaceOne({_id:originalVerification._id},originalVerification,{upsert:true});await mongoose.disconnect()}
}
